ALTER TYPE "public"."DrugTypeEnum" ADD VALUE IF NOT EXISTS 'CNS_DEPRESSANTS';
ALTER TYPE "public"."DrugTypeEnum" ADD VALUE IF NOT EXISTS 'CNS_STIMULANTS';
ALTER TYPE "public"."DrugTypeEnum" ADD VALUE IF NOT EXISTS 'HALLUCINOGENS';
ALTER TYPE "public"."DrugTypeEnum" ADD VALUE IF NOT EXISTS 'DISSOCIATIVE_ANESTHETICS';
ALTER TYPE "public"."DrugTypeEnum" ADD VALUE IF NOT EXISTS 'NARCOTIC_ANALGESICS';
ALTER TYPE "public"."DrugTypeEnum" ADD VALUE IF NOT EXISTS 'INHALANTS';
ALTER TYPE "public"."DrugTypeEnum" ADD VALUE IF NOT EXISTS 'CANNABIS';
